### ISSUE TITLE
Problem to create a route using angular generator:

### ISSUE THREAD

**Issue by kapit4n** [kapit4n/mockupero#5]
D:\projects\mockup\mockupero-ui>yo angular:route user
module.js:440
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Luis Arce\AppData\Roaming\npm\node_modules\generator-angular\node_modules\yeoman-generator\lib\env\index.js:8:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by larce1212** [comment]
It works in Linux but not in windows

**Comment by wolf-mtwo** [comment]
npm install --save lodash

**Comment by larce1212** [comment]
I tried that solution I didn't work

**Comment by wolf-mtwo** [comment]
maybe "YO" version is lower in your window
