### ISSUE TITLE
Error to save mockups

### ISSUE THREAD

**Issue by kapit4n** [kapit4n/mockupero#63]
Error: {"data":{"error":"E_UNKNOWN","status":500,"summary":"Encountered an unexpected error","raw":{}},"status":500,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"project":{"name":"Project 002","description":"This is another example Hello another comment","imgToShow":"","userId":"58bdbef7311a776d1f712711","state":"New","type":"Design","createdAt":"2017-03-22T14:25:27.665Z","updatedAt":"2017-03-23T17:12:53.879Z","id":"58d28957b0be53ac1a6acb34"},"owner":{"email":"admin22@gmail.com","createdAt":"2017-03-06T19:56:39.337Z","updatedAt":"2017-03-09T18:54:15.779Z","firstName":"Admin22","lastName":"Last Name","username":"admin22","id":"58bdbef7311a776d1f712711"},"name":"Mockup 003","width":"500","height":"500","state":"New","description":"Mockup description","imgToShow":"http://blogs.atlassian.com/news/2009/09/10/SimpleLoginScreen-thumb-250x179.png","createdAt":"2017-03-22T14:46:13.395Z","updatedAt":"2017-03-23T17:12:53.873Z","links":[],"id":"58d28e35b0be53ac1a6acb3e"},"url":"http://localhost:1337/mockup/58d28e35b0be53ac1a6acb3e","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"withCredentials":true},"statusText":"Internal Server Error"}

**Comment by kapit4n** [comment]
{"data":{"error":"E_UNKNOWN","status":500,"summary":"Encountered an unexpected error","raw":{}},"status":500,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"project":{"name":"TODO BUY","description":"This is a todo buy project.","imgToShow":"","userId":"5942eea65feebd477601664a","state":"New","type":"Design","createdAt":"2017-06-15T20:32:21.569Z","updatedAt":"2017-06-15T20:51:35.077Z","id":"5942eed55feebd477601664c"},"owner":{"email":"larce21@gmail.com","createdAt":"2017-06-15T20:31:34.847Z","updatedAt":"2017-06-15T20:38:36.014Z","firstName":"Luis","lastName":"Arce","username":"larce","id":"5942eea65feebd477601664a"},"name":"TODO BUY List","width":"800","height":"400","description":"ss","state":"New","imgToShow":"http://blogs.atlassian.com/news/2009/09/10/SimpleLoginScreen-thumb-250x179.png","createdAt":"2017-06-15T20:48:45.255Z","updatedAt":"2017-06-15T20:51:35.018Z","links":[],"id":"5942f2ad5feebd477601665c"},"url":"http://localhost:1337/mockup/5942f2ad5feebd477601665c","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"withCredentials":true},"statusText":"Internal Server Error"}

**Comment by kapit4n** [comment]
{"data":{"error":"E_UNKNOWN","status":500,"summary":"Encountered an unexpected error","raw":{}},"status":500,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"project":{"name":"One Project","description":"sss","imgToShow":"","userId":"59433213e9b1be6e13f12fc7","state":"New","type":"Design","createdAt":"2017-06-16T01:21:13.386Z","updatedAt":"2017-06-16T01:25:40.300Z","id":"59433289e9b1be6e13f12fca"},"owner":{"email":"larce22@gmail.com","createdAt":"2017-06-16T01:19:15.366Z","updatedAt":"2017-06-16T01:20:21.878Z","firstName":"Luis","lastName":"Arce","username":"larce22@gmail.com","id":"59433213e9b1be6e13f12fc7"},"name":"Login Page","width":"800","height":"500","description":"ss","state":"New","imgToShow":"http://blogs.atlassian.com/news/2009/09/10/SimpleLoginScreen-thumb-250x179.png","createdAt":"2017-06-16T01:23:17.980Z","updatedAt":"2017-06-16T01:25:40.292Z","links":[],"id":"59433305e9b1be6e13f12fce"},"url":"http://localhost:1337/mockup/59433305e9b1be6e13f12fce","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"},"withCredentials":true},"statusText":"Internal Server Error"}

**Comment by kapit4n** [comment]
Server side error.
Error: data and salt arguments required
    at /home/larce/projects/mockupero-api/node_modules/bcrypt/bcrypt.js:98:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: data and salt arguments required
    at /home/larce/projects/mockupero-api/node_modules/bcrypt/bcrypt.js:98:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by kapit4n** [comment]
https://scotch.io/tutorials/easy-node-authentication-setup-and-local

**Comment by kapit4n** [comment]
Error: data and salt arguments required
    at /home/larce/projects/mockuper-api-fix/mockupero-api/node_modules/bcrypt/bcrypt.js:98:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
: data and salt arguments required
    at /home/larce/projects/mockuper-api-fix/mockupero-api/node_modules/bcrypt/bcrypt.js:98:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by kapit4n** [comment]
https://stackoverflow.com/questions/42241113/bcrypt-error-data-and-hash-arguments-required

**Comment by kapit4n** [comment]
https://stackoverflow.com/questions/41570585/error-data-and-salt-arguments-required-am-i-missing-something
